export enum TemporalExpressionType {
  RANGE_EVERY_YEAR = "RANGE_EVERY_YEAR",
  DAY_IN_MONTH = "DAY_IN_MONTH",
  DAY_IN_WEEK = "DAY_IN_WEEK",
  DIFFERENCE = "DIFFERENCE",
  UNION = "UNION",
  INTERSECTION = "INTERSECTION",
}
